@echo off
rem build.cmd - one command builds carrier.exe (x86, debug: /Zi /Od).
rem Regenerate gen\*.inc / gen\import_stubs.cpp first if imports.json changed:
rem   python gen\gen_imports.py ..\imports.json gen
rem
rem gen\it_print_globals.inc (src\print_globals.cpp's --print-globals table)
rem is checked in like gen\game_globals.inc - regenerate it if
rem interop_index.json/it_types.h/it_types_check.c change:
rem   python gen\gen_print_globals.py ..
rem
rem Milestones 11-12 (win32_pilot.md SS3): the LIFTED forms (lift\lifted\*.c,
rem generated by lift\pf_lift.py) and the NATIVE forms (native\*.c) are
rem compiled straight into carrier.exe as C, and bound at their original
rem addresses at run time by src\bind.cpp's 5-byte entry patch. They need
rem gen\ (it_types.h/it_funcs.h/it_globals.h) and lift\lifted\ (pf_rt.h) on
rem the include path; PF_MEM() is the identity here, because the carrier maps
rem the original image at its real base.
setlocal
cd /d "%~dp0"

call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
if errorlevel 1 (
  echo FAILED: could not initialize MSVC x86 build environment
  exit /b 1
)

if not exist obj mkdir obj

rem --- src/ binding (item 1, "src binding, tick-boundary real input, parked
rem timer thread" in NOTES.md): derive gen_bindings.py's --exclude list from
rem whichever functions src\icytower\*.c actually DEFINE, instead of hand-
rem listing them (carrier\gen\scan_src_defs.py scans the .c files for
rem function definitions; see its own docstring). This keeps pf_bindings_src.h
rem from also trying to redirect update_frame/is_solid to their own original
rem address (BINDINGS_NOTES.md "Exclusion") without anyone having to remember
rem to update a hand-written list when src\icytower gains a new file.
set SRC_EXCLUDES=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --src-dir ..\src\icytower') do set SRC_EXCLUDES=%%E
if "%SRC_EXCLUDES%"=="" (
  echo FAILED: scan_src_defs.py found no function definitions in src\icytower
  exit /b 1
)
rem scan_src_defs.py only scans FUNCTION definitions (its own docstring), so
rem a plain data definition src\icytower gains (map.c's
rem `static const int floor_size_modifiers[5]`, added alongside add_floor())
rem is invisible to it and would otherwise be left free for
rem pf_bindings_src.h's game-global macro to redirect - MEASURED this pass:
rem without this, `static const int floor_size_modifiers[5] = {...}`
rem macro-expands into `static const int (*(int(*)[5])0x...)[5] = {...}`,
rem a syntax error (MSVC C2059), the moment map.c is compiled with
rem pf_bindings_src.h force-included. Appended by hand until scan_src_defs.py
rem (carrier/lift territory this pass, not touched here) grows a data-symbol
rem scan of its own.
set SRC_EXCLUDES=%SRC_EXCLUDES%,floor_size_modifiers
echo src/ functions excluded from pf_bindings_src.h (compiled natively): %SRC_EXCLUDES%
python gen\gen_bindings.py --exclude %SRC_EXCLUDES% --guard-define ICYTOWER_BINDINGS_ACTIVE ^
  --out gen\pf_bindings_src.h --types-out gen\pf_bindings_src_types.h
if errorlevel 1 (
  echo FAILED: gen_bindings.py --exclude %SRC_EXCLUDES% ^(regenerating pf_bindings_src.h^)
  exit /b 1
)

rem --- "binding table generated" pass (carrier/NOTES.md): carrier\src\bind.cpp
rem no longer hand-carries the per-function binding table (name/VA/argc/
rem comparison domain) as a C++ literal - gen_bind_table.py derives it fresh
rem every build from scan_src_defs.py (which functions), interop_index.json
rem + it_funcs_table.inc (VA/size/prototype), fn_domains.json (the hand-
rem curated comparison-domain DATA), and THIS file's own link line (which
rem lifted_/native_ forms are actually linked in - see below). Must run
rem before bind.cpp is compiled (the final cl invocation, below); has no
rem dependency on pf_bindings_src.h, so any point before that compile works.
python gen\gen_bind_table.py --root ..
if errorlevel 1 (
  echo FAILED: gen_bind_table.py ^(regenerating gen\bind_table.inc^)
  exit /b 1
)

rem --- compile src/ (the clean port, win32_pilot.md SS7a) as its OWN cl
rem invocation with ONLY pf_bindings_src.h force-included - NOT a global /FI
rem on the whole build, because pf_bindings_src.h pulls in the carrier's
rem type provider (it_types.h via pf_bindings_src_types.h), which redefines
rem BITMAP and collides with windows.h the moment both are seen by one TU
rem (carrier\src\bind.cpp's own header comment documents this exact
rem collision). src\icytower\*.c must also never see it_*.h/pf_*.h by name
rem (src\README.md's purity gate), which force-include already respects: the
rem macro substitution happens without any #include text appearing in the
rem source files themselves.
rem
rem Milestone 12 at scale (carrier/NOTES.md), extended by "binding table
rem generated": every src/icytower/*.c file that DEFINES at least one real
rem game function (an interop_index.json VA - excludes assets_standalone.c's
rem harness-only helpers) is compiled and linked in, split MSVC-vs-GCC-x87
rem mechanically by scan_src_defs.py --list-build-files (does this file
rem contain a genuine `double`/`float` CODE token, comments/strings
rem stripped first - see that script's own header for why this is safer
rem than trusting a hand-maintained list). MSVC's cl.exe (no /arch override
rem on this 32-bit target) compiles `double` through SSE/plain-double
rem codegen, which measurably DIFFERs from the original's genuine 80-bit x87
rem intermediates for a real floating-point function (PROMOTIONS.md;
rem win32_pilot.md SS6a) - the GCC-routed files below get the 32-bit MinGW
rem GCC x87-faithful build instead. Both lists are recomputed every build,
rem so a new src\icytower\*.c file needs no manual addition here.
set MSVC_SRC=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --list-build-files msvc --prefix "..\src\icytower\\"') do set MSVC_SRC=%%E
if "%MSVC_SRC%"=="" (
  echo FAILED: scan_src_defs.py --list-build-files msvc found no files to compile
  exit /b 1
)

rem Some src/ files call real Allegro drawing primitives (makecol,
rem textprintf_ex, ...) or the asset-seam accessors (asset_bitmap,
rem asset_font, ...) - e.g. draw_buffer.c/start_reward.c. Those names are
rem NOT resolved by pf_bindings_src.h alone (game-global/game-function
rem macros only): compiling with only that force-include leaves them as
rem plain undeclared identifiers (C's implicit-int rule, so it still
rem COMPILES) that then fail to LINK, LNK2019 - exactly what
rem carrier/gen/build_blockers.json recorded for both files before this
rem split existed. scan_src_defs.py --extra-fi partitions MSVC_SRC
rem mechanically (CALL-syntax scan against pf_lib_bindings.h's bound names
rem + the 5 asset-seam functions - see its own docstring for why a bare-
rem token scan is unsafe here: control.c's check_control_key(..., int key)
rem parameter is also spelled `key`, Allegro's own keyboard array) into
rem MSVC_SRC_BASE (only pf_bindings_src.h needed) and MSVC_SRC_EXTRA (also
rem needs pf_lib_bindings.h + pf_asset_bindings.h) so each group gets its
rem own cl invocation with the right /FI set - draw_buffer.c's and
rem start_reward.c's own header comments already document and verified
rem this exact recipe.
set MSVC_SRC_BASE=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --list-build-files msvc --extra-fi base --prefix "..\src\icytower\\"') do set MSVC_SRC_BASE=%%E
set MSVC_SRC_EXTRA=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --list-build-files msvc --extra-fi extra --prefix "..\src\icytower\\"') do set MSVC_SRC_EXTRA=%%E

if not "%MSVC_SRC_BASE%"=="" (
  cl /nologo /Zi /Od /W3 /TC /D_CRT_SECURE_NO_WARNINGS ^
    /I gen /FIpf_bindings_src.h ^
    /c %MSVC_SRC_BASE% ^
    /Fo:obj\
  if errorlevel 1 (
    echo FAILED: src\icytower MSVC compile errors above ^(base group^)
    exit /b 1
  )
)

if not "%MSVC_SRC_EXTRA%"=="" (
  cl /nologo /Zi /Od /W3 /TC /D_CRT_SECURE_NO_WARNINGS ^
    /I gen /FIpf_bindings_src.h /FIpf_lib_bindings.h /FIpf_asset_bindings.h ^
    /c %MSVC_SRC_EXTRA% ^
    /Fo:obj\
  if errorlevel 1 (
    echo FAILED: src\icytower MSVC compile errors above ^(Allegro/asset-seam group^)
    exit /b 1
  )
)

rem NOTE 1: gcc.exe DOES need its own bin directory on PATH (MEASURED: it
rem fails to run at all, silently, exit 1, no stderr, if invoked by full
rem path alone under the vcvars32 environment - presumably to find its
rem sibling DLLs, e.g. cc1.exe's own libgcc/zlib1.dll, which this MSYS2
rem build does not resolve purely via "look next to the .exe"). Prepending
rem C:\msys64\mingw32\bin to PATH fixes it; verified no collision with the
rem MSVC toolchain (no link.exe/cl.exe under mingw32\bin), so the prepend is
rem left in place for the rest of this script rather than restored.
rem
rem NOTE 2: %PATH% on this machine contains "...Program Files (x86)..." -
rem an unescaped ")" - so it must never be referenced INSIDE a parenthesized
rem cmd block (classic cmd.exe parser trap: the ")" in the value closes the
rem block early and corrupts everything after it, MEASURED this pass as
rem "\Microsoft was unexpected at this time." on an earlier attempt that
rem restored %OLDPATH% from inside `if errorlevel 1 ( ... )`). The
rem errorlevel checks below are therefore two plain (unparenthesized)
rem statements each, not one parenthesized block.
if not exist obj_gcc mkdir obj_gcc
set GCC_BIN=C:\msys64\mingw32\bin
set PATH=%GCC_BIN%;%PATH%
set GCC=gcc.exe
set GCC_SRC=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --list-build-files gcc --prefix "..\src\icytower\\"') do set GCC_SRC=%%E
if "%GCC_SRC%"=="" (
  echo FAILED: scan_src_defs.py --list-build-files gcc found no files to compile
  exit /b 1
)
for %%F in (%GCC_SRC%) do %GCC% -m32 -mfpmath=387 -mno-sse2 -O2 -fno-asynchronous-unwind-tables -Wall -I gen -include pf_bindings_src.h -c %%F -o obj_gcc\%%~nF.o || (echo FAILED: GCC compile of %%F & exit /b 1)
echo OK: GCC x87 objects built: %GCC_SRC%

rem Object lists for the final link, derived from the SAME two file lists
rem above (not a third hand-maintained list) by swapping each .c for the
rem .obj/.o cl/gcc just produced for it.
set MSVC_OBJS=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --list-build-files msvc --prefix "obj\\" --ext .obj') do set MSVC_OBJS=%%E
set GCC_OBJS=
for /f "delims=" %%E in ('python gen\scan_src_defs.py --list-build-files gcc --prefix "obj_gcc\\" --ext .o') do set GCC_OBJS=%%E

cl /nologo /Zi /Od /EHsc /W3 /D_CRT_SECURE_NO_WARNINGS ^
  /I gen /I lift\lifted ^
  src\main.cpp src\pe_image.cpp src\imports.cpp src\trace.cpp src\wrappers.cpp src\symbols.cpp src\det.cpp src\bind.cpp src\snapshot.cpp ^
  src\headless.cpp src\frame.cpp src\print_globals.cpp ^
  gen\import_stubs.cpp ^
  lift\lifted\lifted_update_frame.c lift\lifted\lifted_is_solid.c lift\lifted\lifted_jump_player.c ^
  native\native_update_frame.c native\native_is_solid.c ^
  %MSVC_OBJS% ^
  %GCC_OBJS% ^
  /Fe:carrier.exe /Fo:obj\ ^
  /link /DYNAMICBASE:NO /FIXED /BASE:0x10000000 /LARGEADDRESSAWARE:NO /SUBSYSTEM:CONSOLE /DEBUG /MAP:obj\carrier.map kernel32.lib user32.lib psapi.lib

if errorlevel 1 (
  echo FAILED: build errors above
  exit /b 1
)
echo OK: carrier\carrier.exe built
endlocal
