// Shared plain-data type + extern declarations for the generated import
// table (gen/import_table.inc, gen/import_names.inc, gen/import_stubs.cpp).
// Hand-written; the three .inc/.cpp files that define these symbols are
// generated by gen/gen_imports.py - see that script's DO-NOT-EDIT header.
#pragma once

// Upper bound on import count, used to size the fixed global counter/policy
// arrays below so every translation unit agrees on layout without needing
// the generated (compile-time-constant-in-one-TU-only) kNumImports as an
// array bound. imports.json currently has 320 entries; this leaves room to
// grow without regenerating array declarations.
#define PF_MAX_IMPORTS 512

struct ImportEntry {
    const char* dll;   // e.g. "KERNEL32.dll"
    const char* name;  // e.g. "ExitProcess"
    unsigned long iat_va; // guest VA of the IAT slot this import resolves into
    int id;             // 0..kNumImports-1, matches g_real[]/g_import_stubs[] index
};

extern "C" {
    extern const ImportEntry g_import_table[]; // gen/import_table.inc, imports.cpp
    extern const int kNumImports;               // gen/import_table.inc
    extern const char* g_import_names[];         // gen/import_names.inc
    extern void* g_import_stubs[];               // gen/import_stubs.cpp
    extern void* g_real[PF_MAX_IMPORTS];          // imports.cpp: resolved real proc per id
}
