// symbols.cpp - see symbols.hpp. Deliberately not a general JSON parser:
// artifacts/functions.json is machine-generated by tools_recon/build_functions.py
// with a fixed, verified key order per object ("name","va","size",...), so a
// tiny scanner that hunts for those three literal keys in order is sufficient
// and much smaller than a real parser. If the generator's shape ever changes
// this will start returning fewer symbols, not crash (fail-soft by design).
#include "symbols.hpp"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <vector>

struct Sym {
    unsigned long va;
    unsigned long size;
    char name[128];
};

static std::vector<Sym> g_syms;

// Finds literal `needle` starting at *p (within [p, end)), returns pointer
// just past it, or nullptr if not found before `end`.
static const char* skip_past(const char* p, const char* end, const char* needle) {
    size_t len = strlen(needle);
    for (; p + len <= end; ++p) {
        if (memcmp(p, needle, len) == 0) return p + len;
    }
    return nullptr;
}

bool symbols_load(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "symbols_load: cannot open '%s' (symbol names will be unavailable)\n", path);
        return false;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(sz + 1);
    if (fread(buf, 1, sz, f) != (size_t)sz) { fclose(f); free(buf); return false; }
    fclose(f);
    buf[sz] = 0;
    const char* end = buf + sz;
    const char* p = buf;

    while ((p = skip_past(p, end, "\"name\"")) != nullptr) {
        const char* q = skip_past(p, end, "\"");
        if (!q) break;
        const char* name_start = q;
        const char* name_end = (const char*)memchr(q, '"', end - q);
        if (!name_end) break;

        const char* r = skip_past(name_end, end, "\"va\"");
        if (!r) break;
        r = skip_past(r, end, "\"0x");
        if (!r) break;
        unsigned long va = strtoul(r, nullptr, 16);

        const char* s = skip_past(r, end, "\"size\"");
        if (!s) break;
        s = skip_past(s, end, ":");
        if (!s) break;
        unsigned long size = strtoul(s, nullptr, 10);

        Sym sym;
        sym.va = va;
        sym.size = size;
        size_t nlen = (size_t)(name_end - name_start);
        if (nlen >= sizeof(sym.name)) nlen = sizeof(sym.name) - 1;
        memcpy(sym.name, name_start, nlen);
        sym.name[nlen] = 0;
        g_syms.push_back(sym);

        p = s;
    }
    free(buf);

    std::sort(g_syms.begin(), g_syms.end(),
              [](const Sym& a, const Sym& b) { return a.va < b.va; });

    fprintf(stderr, "symbols_load: loaded %zu functions from '%s'\n", g_syms.size(), path);
    return !g_syms.empty();
}

void symbols_describe(unsigned long va, char* buf, int buf_size) {
    if (g_syms.empty()) {
        _snprintf(buf, buf_size, "<no-symbols>+0x%lx", va);
        buf[buf_size - 1] = 0;
        return;
    }
    // Largest entry whose va <= target.
    size_t lo = 0, hi = g_syms.size();
    while (lo < hi) {
        size_t mid = (lo + hi) / 2;
        if (g_syms[mid].va <= va) lo = mid + 1; else hi = mid;
    }
    if (lo == 0) {
        _snprintf(buf, buf_size, "<unknown>+0x%lx", va);
        buf[buf_size - 1] = 0;
        return;
    }
    const Sym& s = g_syms[lo - 1];
    unsigned long off = va - s.va;
    if (s.size != 0 && off >= s.size) {
        _snprintf(buf, buf_size, "<unknown>(near %s+0x%lx)+0x%lx", s.name, off, va);
    } else {
        _snprintf(buf, buf_size, "%s+0x%lx", s.name, off);
    }
    buf[buf_size - 1] = 0;
}
