/* icytower_harness_project.c -- Icy Tower's own per-function dispatch for
 * the offline harness's macro-bound world, SRC form.
 *
 * Implements pf_harness_dispatch_src() (port_forge/tools/win32_oracle/
 * pf_harness_dispatch.h), called by the generic src_check.c.
 * pf_harness_dispatch_native() -- the same macro-bound world, but
 * dispatching to carrier/native/'s hand-written alternate-name forms
 * instead -- lives in the SEPARATE file icytower_harness_project_native.c,
 * not here: native_check.exe's build never links src/icytower/*.c, so a
 * dispatch function referencing update_frame()/is_solid()/etc. (this
 * file's own pf_harness_dispatch_src()) must not share a translation unit
 * with one native_check.exe actually links, or the linker would need to
 * resolve every extern this file references even though
 * pf_harness_dispatch_src() itself is never called there.
 *
 * notes/extraction_plan.md S3 calls this out by
 * name -- "the pointer-translation call sites for update_frame/is_solid's
 * ply/map arguments" -- as the project-specific residue once the wire
 * protocol/oracle-invocation mechanism moves to port_forge; this file is
 * that residue for every function this harness checks, not just those two:
 * the Icy function name table, and the couple of places a function reads a
 * pointer VALUE out of guest memory (not an argument, not the address of a
 * PF_MEM()-bound global) that the project's own generated bindings header
 * cannot reach.
 *
 * Hand-written harness plumbing (not generated), and NOT part of src/
 * itself: it is driver/plumbing, not recovered game semantics, and it is
 * fine for it to know about the harness's memory model the way src/ must
 * not.
 *
 * MEMORY MODEL:
 *
 * carrier/lift/harness/pf_bindings_harness.h (the --mem-macro PF_MEM twin
 * of carrier/gen/pf_bindings_src.h, both regenerated by gen_bindings.py,
 * not hand-edited -- see BINDINGS_NOTES.md) is force-included ahead of
 * src/icytower/*.c by build_src.cmd. It binds every game global those
 * files touch through PF_MEM() into pf_harness_mem.h's in-process copy of
 * the image (`pf_guest`).
 *
 * That seam alone is NOT enough for two entry points, and the src-form
 * dispatch below closes the remaining gap by hand at those two call sites
 * (tried first: identity-mapping the whole guest range with VirtualAlloc
 * at its real address, matching how the real carrier maps the image --
 * empirically ruled out: on this Windows build, VirtualQuery shows
 * 0x400000..0x800000 already densely occupied by loader/heap-manager
 * mappings before main() even runs, so a fixed VirtualAlloc there fails):
 *
 *   - is_solid's `m` parameter (and every other pointer-shaped vector
 *     ARGUMENT) arrives as a plain guest VA (matching what the real
 *     carrier would pass, since there a guest VA IS a valid host
 *     pointer); src/icytower/*.c dereferences it directly with no seam of
 *     its own (src/ has none -- that is the point of src/), so pf_tr()
 *     (port_forge/tools/win32_oracle/pf_harness_mem.h) translates it at
 *     the call site instead.
 *   - update_frame()/handle_player_collision_original() take no `ply`
 *     argument: they reach the active player through `ply[player_id]`, a
 *     pointer VALUE the vector generator stored inside guest memory
 *     itself (matching what the real carrier would have stored: a plain
 *     guest VA). Because that value lives in memory, not in an argument
 *     slot, pf_bindings_harness.h's per-global PF_MEM() cannot reach it --
 *     PF_MEM() only ever wraps the address of `ply` itself, not the
 *     pointer VALUE read back out of it at run time. This file performs
 *     the second translation by hand, overwriting that one slot with the
 *     equivalent host pointer immediately before calling into the
 *     function. The comparison domain compared afterwards never includes
 *     the ply[] slot itself, so leaving it translated for the rest of
 *     that dispatch call is harmless.
 *   - add_floor()/update_player() call get_demo() internally, which just
 *     relays the `demo` pointer VALUE verbatim (never dereferencing it
 *     itself) -- a caller that DOES dereference the result needs the same
 *     second translation, performed here for those two entry points.
 *
 * Both fixups are this file knowing where Icy Tower's OWN pointer-shaped
 * state lives (a fact already public in carrier/gen/it_globals.h and
 * notes/promotion_candidates.md) -- src/icytower/*.c itself stays exactly
 * as address-free as it is when compiled into the real carrier.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "it_types.h"
#include "pf_harness_mem.h"
#include "pf_harness_dispatch.h"

#define G_PLAYER_ID 0x4fe518u
#define G_PLY       0x4ff128u
#define G_DEMO      0x4dd250u
/* batch 9 (src/icytower/collision.c) */
#define G_SCREEN    0x4dda8cu      /* Allegro BITMAP *screen */
#define SCREEN_VTABLE_VA 0x7c3100u /* scratch GFX_VTABLE (icytower_specs.py) */
#define RAND_SEED_VA 0x794020u

extern void update_frame(void);
extern int  is_solid(Tmap *, int, int);
extern int  jump_player(Tplayer *, int);
extern void getFloorData(Tmap *, int, int *, int *, int *);
extern void reset_map(Tmap *);
extern void add_combo(Tgame_data *, Tgd_combo *);
extern int  line_intersect(int, int, int, int, int, int, int, int, int *, int *);
extern Tgamepad *get_gamepad(void);
extern int  is_up(Tcontrol *);
extern int  is_down(Tcontrol *);
extern int  is_left(Tcontrol *);
extern int  is_right(Tcontrol *);
extern int  is_fire(Tcontrol *);
extern int  is_pause(Tcontrol *);
extern int  is_enter(Tcontrol *);
extern int  is_any(Tcontrol *);
extern void set_control(Tcontrol *, int, int, int, int, int);
extern void init_control(Tcontrol *);
extern int  check_control_key(Tcontrol *, int);
extern int  get_level(Tmap *, int);
extern void add_jump_sequence(Tgame_data *, Tgd_jump_sequence *);
extern void reset_particles(Tparticle *);
extern void scroll_scroller(Tscroller *, int);
extern void restart_scroller(Tscroller *);
extern void cycle_counter(void);
extern void fps_counter(void);
extern Treplay *get_demo(void);
extern Tcontrol *get_controls(void);
extern void switchedFromProgram(void);
extern void switchedToProgram(void);
extern void clickedCloseButton(void);
extern int  new_rand(void);
extern void update_particle(Tparticle *);
extern int  create_particle(Tparticle *, int, int);
extern int  ok_to_play(void);
extern void add_floor(Tmap *);
extern unsigned int harness_rand_state;
extern void reset_player(Tplayer *);
extern void update_player(Tplayer *);
extern void play_jump_sound(Tplayer *);
extern void handle_player_collision_original(int, int);
extern void handle_player_collision_old(int, int);
extern void handle_player_collision_vector(int, int);
extern void handle_player_collision_vector_2(int, int);
extern void handle_player_collision_combo(int, int);
extern int  start_reward(int);

unsigned int pf_harness_dispatch_src(const char *fn, unsigned int *a, unsigned int nargs)
{
    unsigned int eax = 0;
    (void)nargs;

    if (!strcmp(fn, "update_frame")) {
        /* second translation of the pointer VALUE stored in ply[player_id]
         * -- see this file's header comment. */
        int pid = *(int *)PF_MEM(G_PLAYER_ID);
        unsigned int *slot = (unsigned int *)PF_MEM((unsigned int)(G_PLY + 4u * (unsigned int)pid));
        if (*slot >= PF_GUEST_BASE && *slot < PF_GUEST_BASE + PF_GUEST_SIZE)
            *slot = (unsigned int)(size_t)PF_MEM(*slot);
        update_frame();
        eax = 0;
    } else if (!strcmp(fn, "is_solid")) {
        Tmap *m = (Tmap *)pf_tr(a[0]);
        eax = (unsigned int)is_solid(m, (int)a[1], (int)a[2]);
    } else if (!strcmp(fn, "jump_player")) {
        Tplayer *p = (Tplayer *)pf_tr(a[0]);
        eax = (unsigned int)jump_player(p, (int)a[1]);
    } else if (!strcmp(fn, "getFloorData")) {
        Tmap *m = (Tmap *)pf_tr(a[0]);
        int *fy = (int *)pf_tr(a[2]), *fx1 = (int *)pf_tr(a[3]), *fx2 = (int *)pf_tr(a[4]);
        getFloorData(m, (int)a[1], fy, fx1, fx2);
        eax = 0;
    } else if (!strcmp(fn, "reset_map")) {
        Tmap *m = (Tmap *)pf_tr(a[0]);
        reset_map(m);
        eax = 0;
    } else if (!strcmp(fn, "add_combo")) {
        Tgame_data *gd = (Tgame_data *)pf_tr(a[0]);
        Tgd_combo *c = (Tgd_combo *)pf_tr(a[1]);
        add_combo(gd, c);
        eax = 0;
    } else if (!strcmp(fn, "line_intersect")) {
        int *px = (int *)pf_tr(a[8]), *py = (int *)pf_tr(a[9]);
        eax = (unsigned int)line_intersect((int)a[0], (int)a[1], (int)a[2], (int)a[3],
                                           (int)a[4], (int)a[5], (int)a[6], (int)a[7],
                                           px, py);
    } else if (!strcmp(fn, "get_gamepad")) {
        eax = pf_untr(get_gamepad());
    } else if (!strcmp(fn, "is_up")) {
        eax = (unsigned int)is_up((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_down")) {
        eax = (unsigned int)is_down((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_left")) {
        eax = (unsigned int)is_left((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_right")) {
        eax = (unsigned int)is_right((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_fire")) {
        eax = (unsigned int)is_fire((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_pause")) {
        eax = (unsigned int)is_pause((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_enter")) {
        eax = (unsigned int)is_enter((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "is_any")) {
        eax = (unsigned int)is_any((Tcontrol *)pf_tr(a[0]));
    } else if (!strcmp(fn, "set_control")) {
        Tcontrol *c = (Tcontrol *)pf_tr(a[0]);
        set_control(c, (int)a[1], (int)a[2], (int)a[3], (int)a[4], (int)a[5]);
        eax = 0;
    } else if (!strcmp(fn, "init_control")) {
        Tcontrol *c = (Tcontrol *)pf_tr(a[0]);
        init_control(c);
        eax = 0;
    } else if (!strcmp(fn, "check_control_key")) {
        Tcontrol *c = (Tcontrol *)pf_tr(a[0]);
        eax = (unsigned int)check_control_key(c, (int)a[1]);
    } else if (!strcmp(fn, "get_level")) {
        Tmap *m = (Tmap *)pf_tr(a[0]);
        eax = (unsigned int)get_level(m, (int)a[1]);
    } else if (!strcmp(fn, "add_jump_sequence")) {
        Tgame_data *gd = (Tgame_data *)pf_tr(a[0]);
        Tgd_jump_sequence *js = (Tgd_jump_sequence *)pf_tr(a[1]);
        add_jump_sequence(gd, js);
        eax = 0;
    } else if (!strcmp(fn, "reset_particles")) {
        Tparticle *p = (Tparticle *)pf_tr(a[0]);
        reset_particles(p);
        eax = 0;
    } else if (!strcmp(fn, "scroll_scroller")) {
        Tscroller *sc = (Tscroller *)pf_tr(a[0]);
        scroll_scroller(sc, (int)a[1]);
        eax = 0;
    } else if (!strcmp(fn, "restart_scroller")) {
        Tscroller *sc = (Tscroller *)pf_tr(a[0]);
        restart_scroller(sc);
        eax = 0;
    } else if (!strcmp(fn, "cycle_counter")) {
        cycle_counter();
        eax = 0;
    } else if (!strcmp(fn, "fps_counter")) {
        fps_counter();
        eax = 0;
    } else if (!strcmp(fn, "get_demo")) {
        /* raw pointer VALUE relayed verbatim, never dereferenced by
         * get_demo() itself -- no host/guest translation needed. */
        eax = (unsigned int)(size_t)get_demo();
    } else if (!strcmp(fn, "get_controls")) {
        eax = pf_untr(get_controls());
    } else if (!strcmp(fn, "switchedFromProgram")) {
        switchedFromProgram();
        eax = 0;
    } else if (!strcmp(fn, "switchedToProgram")) {
        switchedToProgram();
        eax = 0;
    } else if (!strcmp(fn, "clickedCloseButton")) {
        clickedCloseButton();
        eax = 0;
    } else if (!strcmp(fn, "new_rand")) {
        eax = (unsigned int)new_rand();
    } else if (!strcmp(fn, "update_particle")) {
        Tparticle *p = (Tparticle *)pf_tr(a[0]);
        update_particle(p);
        eax = 0;
    } else if (!strcmp(fn, "create_particle")) {
        Tparticle *p = (Tparticle *)pf_tr(a[0]);
        eax = (unsigned int)create_particle(p, (int)a[1], (int)a[2]);
    } else if (!strcmp(fn, "ok_to_play")) {
        eax = (unsigned int)ok_to_play();
    } else if (!strcmp(fn, "add_floor")) {
        /* second translation of the pointer VALUE stored in the `demo`
         * global -- add_floor calls get_demo() internally, which just
         * relays that value verbatim. Nothing translates it unless this
         * dispatch does, exactly like update_frame's ply[player_id] fixup
         * above. */
        unsigned int *demo_slot = (unsigned int *)PF_MEM(G_DEMO);
        Tmap *m = (Tmap *)pf_tr(a[0]);
        if (*demo_slot >= PF_GUEST_BASE && *demo_slot < PF_GUEST_BASE + PF_GUEST_SIZE)
            *demo_slot = (unsigned int)(size_t)PF_MEM(*demo_slot);
        harness_rand_state = *(unsigned int *)pf_tr(RAND_SEED_VA);
        add_floor(m);
        eax = 0;
    } else if (!strcmp(fn, "reset_player")) {
        Tplayer *p = (Tplayer *)pf_tr(a[0]);
        reset_player(p);
        eax = 0;
    } else if (!strcmp(fn, "update_player")) {
        /* same `demo` pointer-VALUE fixup as add_floor() above. */
        unsigned int *demo_slot = (unsigned int *)PF_MEM(G_DEMO);
        Tplayer *p = (Tplayer *)pf_tr(a[0]);
        if (*demo_slot >= PF_GUEST_BASE && *demo_slot < PF_GUEST_BASE + PF_GUEST_SIZE)
            *demo_slot = (unsigned int)(size_t)PF_MEM(*demo_slot);
        update_player(p);
        eax = 0;
    } else if (!strcmp(fn, "play_jump_sound")) {
        Tplayer *p = (Tplayer *)pf_tr(a[0]);
        play_jump_sound(p);
        eax = 0;
    } else if (!strcmp(fn, "handle_player_collision_original")) {
        /* same second translation of the pointer VALUE stored in
         * ply[player_id] update_frame() already needs above -- this
         * function reads ply[player_id] internally too (never as a
         * parameter, matching the original's own two ignored args). */
        int pid = *(int *)PF_MEM(G_PLAYER_ID);
        unsigned int *slot = (unsigned int *)PF_MEM((unsigned int)(G_PLY + 4u * (unsigned int)pid));
        if (*slot >= PF_GUEST_BASE && *slot < PF_GUEST_BASE + PF_GUEST_SIZE)
            *slot = (unsigned int)(size_t)PF_MEM(*slot);
        handle_player_collision_original((int)a[0], (int)a[1]);
        eax = 0;
    } else if (!strcmp(fn, "start_reward")) {
        eax = (unsigned int)start_reward((int)a[0]);
    } else if (!strcmp(fn, "handle_player_collision_old") ||
               !strcmp(fn, "handle_player_collision_vector") ||
               !strcmp(fn, "handle_player_collision_vector_2") ||
               !strcmp(fn, "handle_player_collision_combo")) {
        /* batch 9 (src/icytower/collision.c). In THIS world every global
         * these four read -- map/any11../sounds/debug/key/screen -- is
         * already PF_MEM-bound by the generated pf_bindings_harness.h, so
         * unlike the GCC dispatch's collision_pre() there is nothing to
         * sync by hand. Two pointer VALUES stored INSIDE guest memory
         * still need the usual second translation:
         *   ply[player_id]  same as handle_player_collision_original above;
         *   screen -> BITMAP.vtable, two levels deep, so that the vtable's
         *             +0x34 `line` slot (which the vector generator filled
         *             with the SYNTHETIC guest VA the ORIGINAL side's
         *             Oracle hooks) can be replaced by the host address of
         *             harness_trace_line(). Neither the BITMAP nor the
         *             vtable is in the comparison domain, so rewriting
         *             them here is invisible to the diff.
         * NOTE: unverified by execution -- this sandbox has no MSVC cl.exe,
         * so src_check.exe could not be rebuilt or run this pass (see
         * PROMOTIONS.md batch 8/9's own sandbox notes). Written so the
         * specs module's DEFAULT_FUNCS["src"] list stays coherent; every
         * EQUAL claim for these four is from the GCC/x87 build. */
        int pid = *(int *)PF_MEM(G_PLAYER_ID);
        unsigned int *slot = (unsigned int *)PF_MEM((unsigned int)(G_PLY + 4u * (unsigned int)pid));
        unsigned int *screen_slot = (unsigned int *)PF_MEM(G_SCREEN);
        if (*slot >= PF_GUEST_BASE && *slot < PF_GUEST_BASE + PF_GUEST_SIZE)
            *slot = (unsigned int)(size_t)PF_MEM(*slot);
        if (*screen_slot >= PF_GUEST_BASE && *screen_slot < PF_GUEST_BASE + PF_GUEST_SIZE) {
            BITMAP *bmp = (BITMAP *)PF_MEM(*screen_slot);
            bmp->vtable = (GFX_VTABLE *)PF_MEM(SCREEN_VTABLE_VA);
            bmp->vtable->line = harness_trace_line;
            *screen_slot = (unsigned int)(size_t)bmp;
        }
        if (!strcmp(fn, "handle_player_collision_old"))
            handle_player_collision_old((int)a[0], (int)a[1]);
        else if (!strcmp(fn, "handle_player_collision_vector"))
            handle_player_collision_vector((int)a[0], (int)a[1]);
        else if (!strcmp(fn, "handle_player_collision_vector_2"))
            handle_player_collision_vector_2((int)a[0], (int)a[1]);
        else
            handle_player_collision_combo((int)a[0], (int)a[1]);
        eax = 0;
    } else {
        fprintf(stderr, "unknown function '%s'\n", fn);
        exit(2);
    }
    return eax;
}
