/* src_check.c -- SRC-side driver of the offline equivalence check.
 *
 * Same wire protocol as native_check.c / lift_check.c (guest image in,
 * vector file in, result file out), calling the plain update_frame()/
 * is_solid() symbols compiled straight from src/icytower/ instead of
 * native_update_frame()/native_is_solid() or the generated lifted_<f>
 * ones, so lift_check.py's existing vector generation, unicorn oracle and
 * diff logic (carrier/lift/README.md SS7) can be reused unchanged -- only
 * --exe and --form point at this binary. See win32_pilot.md SS7a for what
 * this offline check verifies before src/'s forms are ever bound into the
 * running carrier.
 *
 * Hand-written harness (not generated), and NOT part of src/ itself: it is
 * driver/plumbing, not recovered game semantics, and it is fine for it to
 * know about the carrier's memory model the way src/ must not.
 *
 * MEMORY MODEL:
 *
 * carrier/gen/pf_bindings_harness.h (the --mem-macro PF_MEM twin of
 * carrier/gen/pf_bindings_src.h, both regenerated by gen_bindings.py, not
 * hand-edited -- see BINDINGS_NOTES.md) is force-included ahead of
 * src/icytower/update_frame.c and .../is_solid.c in build_src.cmd. It binds
 * every game global those files touch (reward_time, reward_scale,
 * player_id, ply, logic_count) through PF_MEM() into pf_harness_mem.h's
 * in-process copy of the image (`pf_guest`), exactly like the LIFTED and
 * NATIVE forms already do (build.cmd, build_native.cmd) -- this is the
 * single seam win32_pilot.md SS7a describes.
 *
 * That seam alone is NOT enough for these two functions, though, and this
 * driver closes the remaining gap by hand at the two call sites below
 * (tried first: identity-mapping the whole guest range with VirtualAlloc at
 * its real address, matching how the real carrier maps the image -- empirically
 * ruled out: on this Windows build, VirtualQuery shows 0x400000..0x800000
 * already densely occupied by loader/heap-manager mappings before main()
 * even runs, so a fixed VirtualAlloc there fails):
 *
 *   - is_solid's `m` parameter arrives as a plain guest VA in the vector
 *     (matching what the real carrier would pass, since there a guest VA
 *     IS a valid host pointer); is_solid.c dereferences it directly with no
 *     seam of its own (src/ has none -- that is the point of src/), so this
 *     driver translates it through PF_MEM() at the call site instead,
 *     exactly where carrier/native/native_is_solid.c's own PF_MEM(m) cast
 *     used to live before that translation moved out of the NATIVE form and
 *     into src/is_solid.c's caller.
 *   - update_frame() takes no argument: it reaches the active player through
 *     `ply[player_id]`, a pointer VALUE the vector generator stored inside
 *     guest memory itself (matching what the real carrier would have
 *     stored: a plain guest VA). Because that value lives in memory, not in
 *     an argument slot, pf_bindings_harness.h's per-global PF_MEM() cannot
 *     reach it -- PF_MEM() only ever wraps the address of `ply` itself, not
 *     the pointer VALUE read back out of it at run time. This driver
 *     performs the same second translation carrier/native/
 *     native_update_frame.c used to perform explicitly
 *     (`PF_MEM((unsigned int)(size_t)(*ply)[player_id])`), overwriting that
 *     one slot with the equivalent host pointer immediately before calling
 *     update_frame(). The domain compared afterwards (artifacts/
 *     src_equivalence.json) is reward_time/reward_scale/the Tplayer struct
 *     CONTENTS at PLAYER_VA, never the ply[] slot itself, so leaving the
 *     slot translated for the rest of that iteration is harmless.
 *
 * Both fixups are the harness knowing where the game's OWN pointer-shaped
 * state lives (a fact already public in carrier/gen/it_globals.h and
 * notes/promotion_candidates.md) -- src/icytower/*.c itself stays exactly
 * as address-free as it is when compiled into the real carrier.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "it_types.h"

#define G_PLAYER_ID 0x4fe518u
#define G_PLY       0x4ff128u

unsigned char *pf_guest = 0;
static unsigned char *pf_pristine = 0;

void pf_trap(unsigned int va, const char *why)
{
    fprintf(stderr, "PF_TRAP at %08X: %s\n", va, why);
    exit(3);
}

extern void update_frame(void);
extern int  is_solid(Tmap *, int, int);

static unsigned int rd32(FILE *f)
{
    unsigned int v = 0;
    if (fread(&v, 4, 1, f) != 1) { fprintf(stderr, "short read\n"); exit(2); }
    return v;
}

int main(int argc, char **argv)
{
    FILE *fi, *fo;
    unsigned char *raw;
    unsigned int ndom, nvec, i, j, domlen = 0;
    unsigned int *domva, *domlen_i;
    const char *fn;

    if (argc != 5) {
        fprintf(stderr, "usage: src_check <guest.bin> <vectors.bin> <out.bin> <func>\n");
        return 2;
    }
    fn = argv[4];

    raw = (unsigned char *)malloc(PF_GUEST_SIZE + 8192);
    if (!raw) return 2;
    pf_guest = (unsigned char *)(((size_t)raw + 4095) & ~(size_t)4095);
    pf_pristine = (unsigned char *)malloc(PF_GUEST_SIZE);
    if (!pf_pristine) return 2;

    fi = fopen(argv[1], "rb");
    if (!fi) { fprintf(stderr, "cannot open %s\n", argv[1]); return 2; }
    if (fread(pf_pristine, 1, PF_GUEST_SIZE, fi) != PF_GUEST_SIZE) {
        fprintf(stderr, "guest image is not 0x%X bytes\n", PF_GUEST_SIZE);
        return 2;
    }
    fclose(fi);

    fi = fopen(argv[2], "rb");
    if (!fi) { fprintf(stderr, "cannot open %s\n", argv[2]); return 2; }
    if (rd32(fi) != 0x564C4650u) { fprintf(stderr, "bad vector magic\n"); return 2; }
    if (rd32(fi) != PF_GUEST_SIZE) { fprintf(stderr, "image size mismatch\n"); return 2; }
    ndom = rd32(fi);
    domva = (unsigned int *)malloc(ndom * 4);
    domlen_i = (unsigned int *)malloc(ndom * 4);
    for (i = 0; i < ndom; i++) {
        domva[i] = rd32(fi);
        domlen_i[i] = rd32(fi);
        domlen += domlen_i[i];
    }
    nvec = rd32(fi);

    fo = fopen(argv[3], "wb");
    if (!fo) { fprintf(stderr, "cannot open %s\n", argv[3]); return 2; }
    { unsigned int m = 0x53455250u; fwrite(&m, 4, 1, fo); fwrite(&nvec, 4, 1, fo); }

    for (i = 0; i < nvec; i++) {
        unsigned int nargs, a[8], nwr, eax = 0;
        memcpy(pf_guest, pf_pristine, PF_GUEST_SIZE);
        nargs = rd32(fi);
        if (nargs > 8) { fprintf(stderr, "too many args\n"); return 2; }
        for (j = 0; j < nargs; j++) a[j] = rd32(fi);
        nwr = rd32(fi);
        for (j = 0; j < nwr; j++) {
            unsigned int va = rd32(fi), len = rd32(fi);
            if (va < PF_GUEST_BASE || va + len > PF_GUEST_BASE + PF_GUEST_SIZE) {
                fprintf(stderr, "write outside the guest image\n"); return 2;
            }
            if (fread(pf_guest + (va - PF_GUEST_BASE), 1, len, fi) != len) {
                fprintf(stderr, "short vector read\n"); return 2;
            }
        }

        if (!strcmp(fn, "update_frame")) {
            /* second translation of the pointer VALUE stored in ply[player_id]
             * -- see header comment. */
            int pid = *(int *)PF_MEM(G_PLAYER_ID);
            unsigned int *slot = (unsigned int *)PF_MEM((unsigned int)(G_PLY + 4u * (unsigned int)pid));
            if (*slot >= PF_GUEST_BASE && *slot < PF_GUEST_BASE + PF_GUEST_SIZE)
                *slot = (unsigned int)(size_t)PF_MEM(*slot);
            update_frame();
            eax = 0;
        } else if (!strcmp(fn, "is_solid")) {
            Tmap *m = (a[0] >= PF_GUEST_BASE && a[0] < PF_GUEST_BASE + PF_GUEST_SIZE)
                     ? (Tmap *)PF_MEM(a[0]) : (Tmap *)(size_t)a[0];
            eax = (unsigned int)is_solid(m, (int)a[1], (int)a[2]);
        } else {
            fprintf(stderr, "unknown function '%s'\n", fn);
            return 2;
        }

        fwrite(&eax, 4, 1, fo);
        for (j = 0; j < ndom; j++)
            fwrite(pf_guest + (domva[j] - PF_GUEST_BASE), 1, domlen_i[j], fo);
    }
    fclose(fi);
    fclose(fo);
    printf("src side: %u vectors, %u domain bytes each\n", nvec, domlen);
    return 0;
}
