/* src_check.c -- SRC-side driver of the offline equivalence check.
 *
 * Same wire protocol as native_check.c / lift_check.c (guest image in,
 * vector file in, result file out), calling the plain update_frame()/
 * is_solid() symbols compiled straight from src/icytower/ instead of
 * native_update_frame()/native_is_solid() or the generated lifted_<f>
 * ones, so lift_check.py's existing vector generation, unicorn oracle and
 * diff logic (carrier/lift/README.md SS7) can be reused unchanged -- only
 * --exe and --form point at this binary. See win32_pilot.md SS7a for what
 * this offline check verifies before src/'s forms are ever bound into the
 * running carrier.
 *
 * Hand-written harness (not generated), and NOT part of src/ itself: it is
 * driver/plumbing, not recovered game semantics, and it is fine for it to
 * know about the carrier's memory model the way src/ must not.
 *
 * MEMORY MODEL:
 *
 * carrier/gen/pf_bindings_harness.h (the --mem-macro PF_MEM twin of
 * carrier/gen/pf_bindings_src.h, both regenerated by gen_bindings.py, not
 * hand-edited -- see BINDINGS_NOTES.md) is force-included ahead of
 * src/icytower/update_frame.c and .../is_solid.c in build_src.cmd. It binds
 * every game global those files touch (reward_time, reward_scale,
 * player_id, ply, logic_count) through PF_MEM() into pf_harness_mem.h's
 * in-process copy of the image (`pf_guest`), exactly like the LIFTED and
 * NATIVE forms already do (build.cmd, build_native.cmd) -- this is the
 * single seam win32_pilot.md SS7a describes.
 *
 * That seam alone is NOT enough for these two functions, though, and this
 * driver closes the remaining gap by hand at the two call sites below
 * (tried first: identity-mapping the whole guest range with VirtualAlloc at
 * its real address, matching how the real carrier maps the image -- empirically
 * ruled out: on this Windows build, VirtualQuery shows 0x400000..0x800000
 * already densely occupied by loader/heap-manager mappings before main()
 * even runs, so a fixed VirtualAlloc there fails):
 *
 *   - is_solid's `m` parameter arrives as a plain guest VA in the vector
 *     (matching what the real carrier would pass, since there a guest VA
 *     IS a valid host pointer); is_solid.c dereferences it directly with no
 *     seam of its own (src/ has none -- that is the point of src/), so this
 *     driver translates it through PF_MEM() at the call site instead,
 *     exactly where carrier/native/native_is_solid.c's own PF_MEM(m) cast
 *     used to live before that translation moved out of the NATIVE form and
 *     into src/is_solid.c's caller.
 *   - update_frame() takes no argument: it reaches the active player through
 *     `ply[player_id]`, a pointer VALUE the vector generator stored inside
 *     guest memory itself (matching what the real carrier would have
 *     stored: a plain guest VA). Because that value lives in memory, not in
 *     an argument slot, pf_bindings_harness.h's per-global PF_MEM() cannot
 *     reach it -- PF_MEM() only ever wraps the address of `ply` itself, not
 *     the pointer VALUE read back out of it at run time. This driver
 *     performs the same second translation carrier/native/
 *     native_update_frame.c used to perform explicitly
 *     (`PF_MEM((unsigned int)(size_t)(*ply)[player_id])`), overwriting that
 *     one slot with the equivalent host pointer immediately before calling
 *     update_frame(). The domain compared afterwards (artifacts/
 *     src_equivalence.json) is reward_time/reward_scale/the Tplayer struct
 *     CONTENTS at PLAYER_VA, never the ply[] slot itself, so leaving the
 *     slot translated for the rest of that iteration is harmless.
 *
 * Both fixups are the harness knowing where the game's OWN pointer-shaped
 * state lives (a fact already public in carrier/gen/it_globals.h and
 * notes/promotion_candidates.md) -- src/icytower/*.c itself stays exactly
 * as address-free as it is when compiled into the real carrier.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "it_types.h"

#define G_PLAYER_ID 0x4fe518u
#define G_PLY       0x4ff128u
#define G_DEMO      0x4dd250u
#define RAND_SEED_VA 0x794020u

unsigned char *pf_guest = 0;
static unsigned char *pf_pristine = 0;

void pf_trap(unsigned int va, const char *why)
{
    fprintf(stderr, "PF_TRAP at %08X: %s\n", va, why);
    exit(3);
}

extern void update_frame(void);
extern int  is_solid(Tmap *, int, int);
extern int  jump_player(Tplayer *, int);
extern void getFloorData(Tmap *, int, int *, int *, int *);
extern void reset_map(Tmap *);
extern void add_combo(Tgame_data *, Tgd_combo *);
extern int  line_intersect(int, int, int, int, int, int, int, int, int *, int *);
extern Tgamepad *get_gamepad(void);
extern int  is_up(Tcontrol *);
extern int  is_down(Tcontrol *);
extern int  is_left(Tcontrol *);
extern int  is_right(Tcontrol *);
extern int  is_fire(Tcontrol *);
extern int  is_pause(Tcontrol *);
extern int  is_enter(Tcontrol *);
extern int  is_any(Tcontrol *);
/* batch 3 (2026-09-07) */
extern void set_control(Tcontrol *, int, int, int, int, int);
extern void init_control(Tcontrol *);
extern int  check_control_key(Tcontrol *, int);
extern int  get_level(Tmap *, int);
extern void add_jump_sequence(Tgame_data *, Tgd_jump_sequence *);
extern void reset_particles(Tparticle *);
extern void scroll_scroller(Tscroller *, int);
extern void restart_scroller(Tscroller *);
extern void cycle_counter(void);
extern void fps_counter(void);
extern Treplay *get_demo(void);
extern Tcontrol *get_controls(void);
extern void switchedFromProgram(void);
extern void switchedToProgram(void);
extern void clickedCloseButton(void);
/* batch 4 (2026-09-07) */
extern int  new_rand(void);
extern void update_particle(Tparticle *);
extern int  create_particle(Tparticle *, int, int);
extern int  ok_to_play(void);
/* add_floor pass (2026-09-07): add_floor() calls the game's own rand(),
 * redirected in THIS build only to harness_rand() by pf_harness_rand.h
 * (force-included alongside pf_bindings_harness.h -- see that header's own
 * comment for the full rationale). demo (used by get_demo(), which
 * add_floor() calls internally) is already bound through PF_MEM by
 * pf_bindings_harness.h, so no extra fixup is needed for it here -- only
 * harness_rand_state needs seeding per vector, from RAND_SEED_VA. */
extern void add_floor(Tmap *);
extern unsigned int harness_rand_state;
/* batch 6 (2026-09-07): reset_player() is a plain Tplayer* leaf, same shape
 * as jump_player(). update_player() calls get_demo() internally (for
 * gravity_modifier[get_demo()->gravity]) and dereferences the result, so it
 * needs the exact same `demo` pointer-VALUE fixup add_floor() already
 * established above. */
extern void reset_player(Tplayer *);
extern void update_player(Tplayer *);

static unsigned int rd32(FILE *f)
{
    unsigned int v = 0;
    if (fread(&v, 4, 1, f) != 1) { fprintf(stderr, "short read\n"); exit(2); }
    return v;
}

/* tr()/untr() -- the same guest-VA <-> host-pointer translation src_check's
 * update_frame/is_solid cases already perform by hand at their call sites
 * (see the header comment): a vector's pointer-shaped arguments arrive as
 * plain guest VAs (what the real carrier would pass, since there a guest VA
 * IS a valid host pointer); this driver knows the harness's memory model
 * (src/ itself does not), so it does the PF_MEM() translation here instead
 * of inside the recovered functions. untr() is the inverse, needed once a
 * recovered function hands back a pointer VALUE (get_gamepad's return) that
 * has to be compared against the unicorn oracle's raw guest VA. */
static void *tr(unsigned int va)
{
    if (va >= PF_GUEST_BASE && va < PF_GUEST_BASE + PF_GUEST_SIZE)
        return PF_MEM(va);
    return (void *)(size_t)va;
}

static unsigned int untr(void *hostptr)
{
    unsigned char *p = (unsigned char *)hostptr;
    if (p >= pf_guest && p < pf_guest + PF_GUEST_SIZE)
        return (unsigned int)(PF_GUEST_BASE + (p - pf_guest));
    return (unsigned int)(size_t)hostptr;
}

int main(int argc, char **argv)
{
    FILE *fi, *fo;
    unsigned char *raw;
    unsigned int ndom, nvec, i, j, domlen = 0;
    unsigned int *domva, *domlen_i;
    const char *fn;

    if (argc != 5) {
        fprintf(stderr, "usage: src_check <guest.bin> <vectors.bin> <out.bin> <func>\n");
        return 2;
    }
    fn = argv[4];

    raw = (unsigned char *)malloc(PF_GUEST_SIZE + 8192);
    if (!raw) return 2;
    pf_guest = (unsigned char *)(((size_t)raw + 4095) & ~(size_t)4095);
    pf_pristine = (unsigned char *)malloc(PF_GUEST_SIZE);
    if (!pf_pristine) return 2;

    fi = fopen(argv[1], "rb");
    if (!fi) { fprintf(stderr, "cannot open %s\n", argv[1]); return 2; }
    if (fread(pf_pristine, 1, PF_GUEST_SIZE, fi) != PF_GUEST_SIZE) {
        fprintf(stderr, "guest image is not 0x%X bytes\n", PF_GUEST_SIZE);
        return 2;
    }
    fclose(fi);

    fi = fopen(argv[2], "rb");
    if (!fi) { fprintf(stderr, "cannot open %s\n", argv[2]); return 2; }
    if (rd32(fi) != 0x564C4650u) { fprintf(stderr, "bad vector magic\n"); return 2; }
    if (rd32(fi) != PF_GUEST_SIZE) { fprintf(stderr, "image size mismatch\n"); return 2; }
    ndom = rd32(fi);
    domva = (unsigned int *)malloc(ndom * 4);
    domlen_i = (unsigned int *)malloc(ndom * 4);
    for (i = 0; i < ndom; i++) {
        domva[i] = rd32(fi);
        domlen_i[i] = rd32(fi);
        domlen += domlen_i[i];
    }
    nvec = rd32(fi);

    fo = fopen(argv[3], "wb");
    if (!fo) { fprintf(stderr, "cannot open %s\n", argv[3]); return 2; }
    { unsigned int m = 0x53455250u; fwrite(&m, 4, 1, fo); fwrite(&nvec, 4, 1, fo); }

    for (i = 0; i < nvec; i++) {
        unsigned int nargs, a[10], nwr, eax = 0;
        memcpy(pf_guest, pf_pristine, PF_GUEST_SIZE);
        nargs = rd32(fi);
        if (nargs > 10) { fprintf(stderr, "too many args\n"); return 2; }
        for (j = 0; j < nargs; j++) a[j] = rd32(fi);
        nwr = rd32(fi);
        for (j = 0; j < nwr; j++) {
            unsigned int va = rd32(fi), len = rd32(fi);
            if (va < PF_GUEST_BASE || va + len > PF_GUEST_BASE + PF_GUEST_SIZE) {
                fprintf(stderr, "write outside the guest image\n"); return 2;
            }
            if (fread(pf_guest + (va - PF_GUEST_BASE), 1, len, fi) != len) {
                fprintf(stderr, "short vector read\n"); return 2;
            }
        }

        if (!strcmp(fn, "update_frame")) {
            /* second translation of the pointer VALUE stored in ply[player_id]
             * -- see header comment. */
            int pid = *(int *)PF_MEM(G_PLAYER_ID);
            unsigned int *slot = (unsigned int *)PF_MEM((unsigned int)(G_PLY + 4u * (unsigned int)pid));
            if (*slot >= PF_GUEST_BASE && *slot < PF_GUEST_BASE + PF_GUEST_SIZE)
                *slot = (unsigned int)(size_t)PF_MEM(*slot);
            update_frame();
            eax = 0;
        } else if (!strcmp(fn, "is_solid")) {
            Tmap *m = (Tmap *)tr(a[0]);
            eax = (unsigned int)is_solid(m, (int)a[1], (int)a[2]);
        } else if (!strcmp(fn, "jump_player")) {
            Tplayer *p = (Tplayer *)tr(a[0]);
            eax = (unsigned int)jump_player(p, (int)a[1]);
        } else if (!strcmp(fn, "getFloorData")) {
            Tmap *m = (Tmap *)tr(a[0]);
            int *fy = (int *)tr(a[2]), *fx1 = (int *)tr(a[3]), *fx2 = (int *)tr(a[4]);
            getFloorData(m, (int)a[1], fy, fx1, fx2);
            eax = 0;
        } else if (!strcmp(fn, "reset_map")) {
            Tmap *m = (Tmap *)tr(a[0]);
            reset_map(m);
            eax = 0;
        } else if (!strcmp(fn, "add_combo")) {
            Tgame_data *gd = (Tgame_data *)tr(a[0]);
            Tgd_combo *c = (Tgd_combo *)tr(a[1]);
            add_combo(gd, c);
            eax = 0;
        } else if (!strcmp(fn, "line_intersect")) {
            int *px = (int *)tr(a[8]), *py = (int *)tr(a[9]);
            eax = (unsigned int)line_intersect((int)a[0], (int)a[1], (int)a[2], (int)a[3],
                                               (int)a[4], (int)a[5], (int)a[6], (int)a[7],
                                               px, py);
        } else if (!strcmp(fn, "get_gamepad")) {
            eax = untr(get_gamepad());
        } else if (!strcmp(fn, "is_up")) {
            eax = (unsigned int)is_up((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_down")) {
            eax = (unsigned int)is_down((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_left")) {
            eax = (unsigned int)is_left((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_right")) {
            eax = (unsigned int)is_right((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_fire")) {
            eax = (unsigned int)is_fire((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_pause")) {
            eax = (unsigned int)is_pause((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_enter")) {
            eax = (unsigned int)is_enter((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "is_any")) {
            eax = (unsigned int)is_any((Tcontrol *)tr(a[0]));
        } else if (!strcmp(fn, "set_control")) {
            Tcontrol *c = (Tcontrol *)tr(a[0]);
            set_control(c, (int)a[1], (int)a[2], (int)a[3], (int)a[4], (int)a[5]);
            eax = 0;
        } else if (!strcmp(fn, "init_control")) {
            Tcontrol *c = (Tcontrol *)tr(a[0]);
            init_control(c);
            eax = 0;
        } else if (!strcmp(fn, "check_control_key")) {
            Tcontrol *c = (Tcontrol *)tr(a[0]);
            eax = (unsigned int)check_control_key(c, (int)a[1]);
        } else if (!strcmp(fn, "get_level")) {
            Tmap *m = (Tmap *)tr(a[0]);
            eax = (unsigned int)get_level(m, (int)a[1]);
        } else if (!strcmp(fn, "add_jump_sequence")) {
            Tgame_data *gd = (Tgame_data *)tr(a[0]);
            Tgd_jump_sequence *js = (Tgd_jump_sequence *)tr(a[1]);
            add_jump_sequence(gd, js);
            eax = 0;
        } else if (!strcmp(fn, "reset_particles")) {
            Tparticle *p = (Tparticle *)tr(a[0]);
            reset_particles(p);
            eax = 0;
        } else if (!strcmp(fn, "scroll_scroller")) {
            Tscroller *sc = (Tscroller *)tr(a[0]);
            scroll_scroller(sc, (int)a[1]);
            eax = 0;
        } else if (!strcmp(fn, "restart_scroller")) {
            Tscroller *sc = (Tscroller *)tr(a[0]);
            restart_scroller(sc);
            eax = 0;
        } else if (!strcmp(fn, "cycle_counter")) {
            cycle_counter();
            eax = 0;
        } else if (!strcmp(fn, "fps_counter")) {
            fps_counter();
            eax = 0;
        } else if (!strcmp(fn, "get_demo")) {
            /* raw pointer VALUE relayed verbatim, never dereferenced by
             * get_demo() itself -- no host/guest translation needed. */
            eax = (unsigned int)(size_t)get_demo();
        } else if (!strcmp(fn, "get_controls")) {
            eax = untr(get_controls());
        } else if (!strcmp(fn, "switchedFromProgram")) {
            switchedFromProgram();
            eax = 0;
        } else if (!strcmp(fn, "switchedToProgram")) {
            switchedToProgram();
            eax = 0;
        } else if (!strcmp(fn, "clickedCloseButton")) {
            clickedCloseButton();
            eax = 0;
        } else if (!strcmp(fn, "new_rand")) {
            eax = (unsigned int)new_rand();
        } else if (!strcmp(fn, "update_particle")) {
            Tparticle *p = (Tparticle *)tr(a[0]);
            update_particle(p);
            eax = 0;
        } else if (!strcmp(fn, "create_particle")) {
            Tparticle *p = (Tparticle *)tr(a[0]);
            eax = (unsigned int)create_particle(p, (int)a[1], (int)a[2]);
        } else if (!strcmp(fn, "ok_to_play")) {
            eax = (unsigned int)ok_to_play();
        } else if (!strcmp(fn, "add_floor")) {
            /* second translation of the pointer VALUE stored in the `demo`
             * global -- add_floor calls get_demo() internally, which just
             * relays that value verbatim (see get_demo's own PROMOTIONS.md
             * entry: "never dereferenced ... so no host/guest translation
             * is needed anywhere" -- true for get_demo() alone, not for a
             * caller that dereferences the result). Nothing translates it
             * unless this driver does, exactly like the update_frame
             * ply[player_id] fixup above. */
            unsigned int *demo_slot = (unsigned int *)PF_MEM(G_DEMO);
            Tmap *m = (Tmap *)tr(a[0]);
            if (*demo_slot >= PF_GUEST_BASE && *demo_slot < PF_GUEST_BASE + PF_GUEST_SIZE)
                *demo_slot = (unsigned int)(size_t)PF_MEM(*demo_slot);
            harness_rand_state = *(unsigned int *)tr(RAND_SEED_VA);
            add_floor(m);
            eax = 0;
        } else if (!strcmp(fn, "reset_player")) {
            Tplayer *p = (Tplayer *)tr(a[0]);
            reset_player(p);
            eax = 0;
        } else if (!strcmp(fn, "update_player")) {
            /* same `demo` pointer-VALUE fixup as add_floor() above. */
            unsigned int *demo_slot = (unsigned int *)PF_MEM(G_DEMO);
            Tplayer *p = (Tplayer *)tr(a[0]);
            if (*demo_slot >= PF_GUEST_BASE && *demo_slot < PF_GUEST_BASE + PF_GUEST_SIZE)
                *demo_slot = (unsigned int)(size_t)PF_MEM(*demo_slot);
            update_player(p);
            eax = 0;
        } else {
            fprintf(stderr, "unknown function '%s'\n", fn);
            return 2;
        }

        fwrite(&eax, 4, 1, fo);
        for (j = 0; j < ndom; j++)
            fwrite(pf_guest + (domva[j] - PF_GUEST_BASE), 1, domlen_i[j], fo);
    }
    fclose(fi);
    fclose(fo);
    printf("src side: %u vectors, %u domain bytes each\n", nvec, domlen);
    return 0;
}
